name: Run semantic-release

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: radiorabe/actions/.github/workflows/semantic-release.yaml@main
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
